### ISSUE TITLE
Parallel build failure: fatal error: libgcc_tm.h: No such file or directory

### ISSUE THREAD

**Issue by ryandesign** [iains/gcc-darwin-arm64#61] opened 2021-12-10 17:54 UTC
Building the latest gcc source from this repo (at least up to a3a48770291014cf1a73a4d2e032fbe13c2deec6  anyway) fails intermittently with:

```
fatal error: libgcc_tm.h: No such file or directory
```

This was reported to MacPorts by three users here:

* https://trac.macports.org/ticket/63879
* https://trac.macports.org/ticket/64124

and was also experienced by the MacPorts automated build system here:

* https://build.macports.org/builders/ports-11_arm64-builder/builds/37283/steps/install-port/logs/stdio/text

One user reported success when not using parallel building (when not using e.g. `make -j8`); another reported success when retrying the build without cleaning first.

I don't know if this is an upstream gcc problem or is specific to this fork, but since two of the reporters were using Apple Silicon machines (and thus this fork) and the third reporter didn't specify, I thought I'd start by reporting the problem here.

A similar problem was reported to gcc a long time ago and fixed:

* https://gcc.gnu.org/bugzilla/show_bug.cgi?id=50991

**Comment by iains** [comment] 2021-12-10 18:10
* Firstly, I apologise - but at the moment I have no build system (gcc304 is offline) so I'm relying on others to bootstrap & test.

* The aarch64 port should not require libgcc_tm.h now [as of  1cd4f4450ffbf734baf3e427f2d6e1d2e83e9c0e ]
(the libgcc_tm.h  header  is only needed to build the EH shim for the Darwin10 missing find function - which is irrelevant to aarach64 since we obv do not support Darwin10).

* The main changes are in upstream commits (to fix long-standing EH hassles) - but AFAIK dependencies are OK(at least my j16 builds on x86_64 -j12 on i686 and -j4 on powerpc have no issues)

----

However - the current source [ 1cd4f4450ffbf734baf3e427f2d6e1d2e83e9c0e] needs a small patch to bootstrap.

Please wait for this weekend's rebase -- Sunday perhaps.

**Comment by iains** [comment] 2021-12-15 12:32
As of
https://github.com/iains/gcc-darwin-arm64/commit/fb3177f9479b0b25a3699c43bf378dd17846d733

I believe that this is OK on aarch64-darwin20/21
 - the deps on libgcc_tm.h are in place
 - none of the new infrastructure that is used to support a legacy libgcc_s.1.dylib is now built on aarch64 darwin, since that will never have a libgcc_s.1.dylib in a released version (if there are any deps in unofficial current code, they will have to be cleaned up after the first release).  Let's not collect cruft before we even start in a new port ....

full disclosure: There is a latent race condition in building the new shared EH lib that shows up on powerpc-darwin9 [but I didn't manage to reproduce on any other platform]  (this will be fixed in the next build cycle).

this cycle took a while - because of lack of access to hardware at the moment.

**Comment by iains** [comment] 2021-12-18 20:52
is this now working for you? (a new update has been posted today, which certainly builds -j8 for me).

**Comment by michaelld** [comment] 2021-12-22 21:30
I just updated `gcc-devel` to the latest commit, and in my testing parallel build works ... but I've only tried it twice. I left the command to disable parallel builds in place until others have had a chance to do testing.

**Comment by iains** [comment] 2021-12-22 21:32
thanks, keep me posted - I've bootstrapped and tested at least half a dozen times over the last few days, and I suspect @fxcoudert has too.

**Comment by michaelld** [comment] 2022-01-04 14:57
@iains FYI I re-enabled parallel builds for ARM64 `gcc-devel` port yesterday https://github.com/macports/macports-ports/commit/6b34373ca200cde3bc567c105969fb2e3af73925

**Comment by michaelld** [comment] 2022-01-04 15:01
I'd say go ahead and close this

**Comment by iains** [comment] 2022-01-04 15:11
great! thanks for letting us know

**Closed by iains** 2022-01-04 15:11 UTC
