### ISSUE TITLE
C++: large vectors give unexpected token in '.section' directive

### ISSUE THREAD

**Issue by fxcoudert** [iains/gcc-darwin-arm64#107] opened 2023-05-26 14:21 UTC
Works with clang but not GCC on ARM darwin:

```
$ cat a.cpp
#include<vector>

std::vector<int> factor[50000];

int main() { return 0; }
$ clang++ a.cpp
$ g++-13 a.cpp 
/var/folders/h8/9hx_fyj91053ksgdzb2w03vw0000gp/T//cc1UFPyo.s:365:29: error: unexpected token in '.section' directive
        .section .data.rel.ro.local
                                   ^
```

**Comment by iains** [comment] 2023-05-26 14:24
I have read in other reports that this is a gcc-13 regression, can you confirm?

**Comment by iains** [comment] 2023-05-26 15:36
> I have read in other reports that this is a gcc-13 regression, can you confirm?

answering ; no it's not a gcc-13 regression - but it is a gcc-12 regression.
from a quick look the problem was always there (aarch64 port is trying to use ELF sections on Mach-O because it's overriding what's set in the target header).  I guess there was some 11 = > 12  code-gen change that favours use of a relocated literal in this case.  

[I think] we just need to make sure to use the mach-o section selector.

**Comment by iains** [comment] 2023-05-26 22:13
so, fixed on trunk - but needs back porting.

**Closed by iains** 2023-05-26 22:13 UTC
