### ISSUE TITLE
error: index must be an integer in range [-256, 255]

### ISSUE THREAD

**Issue by ilg-ul** [iains/gcc-darwin-arm64#54] opened 2021-11-27 18:47 UTC
While compiling perl 5.34.0, I get lots of errors mentioning assembly code:

```
gcc-xbs -c -DPERL_CORE -I/Users/ilg/.local/xbb/include -pipe -O2 -ffunction-sections -fdata-sections -mmacosx-version-min=11.0 -w -fwrapv -fno-strict-aliasing -fstack-protector-strong -DPERL_USE_SAFE_PUTENV -std=c89 -O3 -Wall -Werror=pointer-arith -Wextra -Wc++-compat -Wwrite-strings -Werror=declaration-after-statement pad.c
<stdin>:1580:15: error: index must be an integer in range [-256, 255].
        ldr     x6, [x6, ___stack_chk_guard];momd
```

I did not study the source code to see if it is legit, but at first sight it is C, so assembly errors are not expected.

The build logs are attached.

[perl-5.34.0.zip](https://github.com/iains/gcc-darwin-arm64/files/7612246/perl-5.34.0.zip)

`gcc-xbb` is from the latest HomeBrew branch.

Building with Apple clang is ok.

**Comment by iains** [comment] 2021-11-27 19:26
please could you isolate an example failing command line and re-run that with "-save-temps" and attach the pre-processed file - there's no realistic way for me to reproduce your complete build environment.

**Comment by ilg-ul** [comment] 2021-11-28 06:05
Command:

```
Last login: Sat Nov 27 21:55:40 on ttys005
ilg@xbbma perl-5.34.0 % /Users/ilg/.local/xbb-bootstrap/usr/bin/gcc-xbs -c -DPERL_CORE -I/Users/ilg/.local/xbb/include -pipe -O2 -ffunction-sections -fdata-sections -mmacosx-version-min=11.0 -w -fwrapv -fno-strict-aliasing -fstack-protector-strong -DPERL_USE_SAFE_PUTENV -std=c89 -O3 -Wall -Werror=pointer-arith -Wextra -Wc++-compat -Wwrite-strings -Werror=declaration-after-statement util.c -save-temps
gcc-xbs: warning: '-pipe' ignored because '-save-temps' specified
util.s:437:15: error: index must be an integer in range [-256, 255].
        ldr     x6, [x5, ___stack_chk_guard];momd
                         ^
util.s:519:15: error: index must be an integer in range [-256, 255].
        ldr     x0, [x0, ___stack_chk_guard];momd
                         ^
util.s:1193:15: error: index must be an integer in range [-256, 255].
        ldr     x3, [x3, ___stack_chk_guard];momd
                         ^
util.s:1280:15: error: index must be an integer in range [-256, 255].
        ldr     x0, [x0, ___stack_chk_guard];momd
                         ^
util.s:1511:15: error: index must be an integer in range [-256, 255].
        ldr     x4, [x2, ___stack_chk_guard];momd
                         ^
util.s:1531:15: error: index must be an integer in range [-256, 255].
        ldr     x1, [x1, ___stack_chk_guard];momd
                         ^
util.s:1680:15: error: index must be an integer in range [-256, 255].
        ldr     x4, [x2, ___stack_chk_guard];momd
                         ^
util.s:1697:15: error: index must be an integer in range [-256, 255].
        ldr     x1, [x1, ___stack_chk_guard];momd
                         ^
util.s:1771:15: error: index must be an integer in range [-256, 255].
        ldr     x3, [x3, ___stack_chk_guard];momd
                         ^
util.s:1921:15: error: index must be an integer in range [-256, 255].
        ldr     x1, [x1, ___stack_chk_guard];momd
                         ^
util.s:2034:15: error: index must be an integer in range [-256, 255].
        ldr     x1, [x1, ___stack_chk_guard];momd
                         ^
util.s:2056:15: error: index must be an integer in range [-256, 255].
        ldr     x3, [x3, ___stack_chk_guard];momd
                         ^
util.s:2078:15: error: index must be an integer in range [-256, 255].
        ldr     x1, [x1, ___stack_chk_guard];momd
                         ^
util.s:2236:15: error: index must be an integer in range [-256, 255].
        ldr     x1, [x1, ___stack_chk_guard];momd
                         ^
util.s:2249:15: error: index must be an integer in range [-256, 255].
        ldr     x1, [x1, ___stack_chk_guard];momd
                         ^
util.s:2272:15: error: index must be an integer in range [-256, 255].
        ldr     x3, [x3, ___stack_chk_guard];momd
                         ^
util.s:2281:15: error: index must be an integer in range [-256, 255].
        ldr     x1, [x1, ___stack_chk_guard];momd
                         ^
util.s:2326:15: error: index must be an integer in range [-256, 255].
        ldr     x3, [x3, ___stack_chk_guard];momd
                         ^
util.s:2394:15: error: index must be an integer in range [-256, 255].
        ldr     x2, [x2, ___stack_chk_guard];momd
                         ^
util.s:2682:15: error: index must be an integer in range [-256, 255].
        ldr     x1, [x1, ___stack_chk_guard];momd
                         ^
util.s:2695:15: error: index must be an integer in range [-256, 255].
        ldr     x1, [x1, ___stack_chk_guard];momd
                         ^
util.s:2718:15: error: index must be an integer in range [-256, 255].
        ldr     x3, [x3, ___stack_chk_guard];momd
                         ^
util.s:2727:15: error: index must be an integer in range [-256, 255].
        ldr     x1, [x1, ___stack_chk_guard];momd
                         ^
util.s:2766:15: error: index must be an integer in range [-256, 255].
        ldr     x3, [x3, ___stack_chk_guard];momd
                         ^
util.s:2820:15: error: index must be an integer in range [-256, 255].
        ldr     x3, [x3, ___stack_chk_guard];momd
                         ^
util.s:2965:15: error: index must be an integer in range [-256, 255].
        ldr     x0, [x0, ___stack_chk_guard];momd
                         ^
util.s:2982:15: error: index must be an integer in range [-256, 255].
        ldr     x0, [x0, ___stack_chk_guard];momd
                         ^
util.s:3041:15: error: index must be an integer in range [-256, 255].
        ldr     x3, [x3, ___stack_chk_guard];momd
                         ^
util.s:3186:15: error: index must be an integer in range [-256, 255].
        ldr     x0, [x0, ___stack_chk_guard];momd
                         ^
util.s:3203:15: error: index must be an integer in range [-256, 255].
        ldr     x0, [x0, ___stack_chk_guard];momd
                         ^
util.s:3266:15: error: index must be an integer in range [-256, 255].
        ldr     x1, [x1, ___stack_chk_guard];momd
                         ^
util.s:3279:15: error: index must be an integer in range [-256, 255].
        ldr     x0, [x0, ___stack_chk_guard];momd
                         ^
util.s:3302:15: error: index must be an integer in range [-256, 255].
        ldr     x3, [x3, ___stack_chk_guard];momd
                         ^
util.s:3311:15: error: index must be an integer in range [-256, 255].
        ldr     x0, [x0, ___stack_chk_guard];momd
                         ^
util.s:3441:15: error: index must be an integer in range [-256, 255].
        ldr     x2, [x2, ___stack_chk_guard];momd
                         ^
util.s:3455:15: error: index must be an integer in range [-256, 255].
        ldr     x0, [x0, ___stack_chk_guard];momd
                         ^
util.s:3478:15: error: index must be an integer in range [-256, 255].
        ldr     x4, [x4, ___stack_chk_guard];momd
                         ^
util.s:3487:15: error: index must be an integer in range [-256, 255].
        ldr     x0, [x0, ___stack_chk_guard];momd
                         ^
util.s:3551:15: error: index must be an integer in range [-256, 255].
        ldr     x3, [x3, ___stack_chk_guard];momd
                         ^
util.s:3567:15: error: index must be an integer in range [-256, 255].
        ldr     x0, [x0, ___stack_chk_guard];momd
                         ^
util.s:3638:15: error: index must be an integer in range [-256, 255].
        ldr     x3, [x3, ___stack_chk_guard];momd
                         ^
util.s:3654:15: error: index must be an integer in range [-256, 255].
        ldr     x0, [x0, ___stack_chk_guard];momd
                         ^
util.s:3935:15: error: index must be an integer in range [-256, 255].
        ldr     x3, [x3, ___stack_chk_guard];momd
                         ^
util.s:3946:15: error: index must be an integer in range [-256, 255].
        ldr     x1, [x1, ___stack_chk_guard];momd
                         ^
util.s:3984:15: error: index must be an integer in range [-256, 255].
        ldr     x3, [x3, ___stack_chk_guard];momd
                         ^
util.s:3994:15: error: index must be an integer in range [-256, 255].
        ldr     x1, [x1, ___stack_chk_guard];momd
                         ^
util.s:4019:15: error: index must be an integer in range [-256, 255].
        ldr     x4, [x4, ___stack_chk_guard];momd
                         ^
util.s:4037:15: error: index must be an integer in range [-256, 255].
        ldr     x1, [x1, ___stack_chk_guard];momd
                         ^
util.s:4142:15: error: index must be an integer in range [-256, 255].
        ldr     x4, [x4, ___stack_chk_guard];momd
                         ^
util.s:4277:15: error: index must be an integer in range [-256, 255].
        ldr     x1, [x1, ___stack_chk_guard];momd
                         ^
util.s:4424:15: error: index must be an integer in range [-256, 255].
        ldr     x3, [x3, ___stack_chk_guard];momd
                         ^
util.s:4522:15: error: index must be an integer in range [-256, 255].
        ldr     x1, [x1, ___stack_chk_guard];momd
                         ^
util.s:4734:15: error: index must be an integer in range [-256, 255].
        ldr     x2, [x2, ___stack_chk_guard];momd
                         ^
util.s:4789:15: error: index must be an integer in range [-256, 255].
        ldr     x0, [x0, ___stack_chk_guard];momd
                         ^
util.s:5077:15: error: index must be an integer in range [-256, 255].
        ldr     x3, [x3, ___stack_chk_guard];momd
                         ^
util.s:5105:15: error: index must be an integer in range [-256, 255].
        ldr     x0, [x0, ___stack_chk_guard];momd
                         ^
util.s:6020:15: error: index must be an integer in range [-256, 255].
        ldr     x2, [x2, ___stack_chk_guard];momd
                         ^
util.s:6074:15: error: index must be an integer in range [-256, 255].
        ldr     x0, [x0, ___stack_chk_guard];momd
                         ^
util.s:6430:15: error: index must be an integer in range [-256, 255].
        ldr     x2, [x2, ___stack_chk_guard];momd
                         ^
util.s:6521:15: error: index must be an integer in range [-256, 255].
        ldr     x0, [x0, ___stack_chk_guard];momd
                         ^
util.s:6585:15: error: index must be an integer in range [-256, 255].
        ldr     x2, [x2, ___stack_chk_guard];momd
                         ^
util.s:6610:15: error: index must be an integer in range [-256, 255].
        ldr     x1, [x1, ___stack_chk_guard];momd
                         ^
util.s:7239:15: error: index must be an integer in range [-256, 255].
        ldr     x1, [x1, ___stack_chk_guard];momd
                         ^
util.s:7679:15: error: index must be an integer in range [-256, 255].
        ldr     x0, [x0, ___stack_chk_guard];momd
                         ^
util.s:8640:15: error: index must be an integer in range [-256, 255].
        ldr     x2, [x2, ___stack_chk_guard];momd
                         ^
util.s:8691:15: error: index must be an integer in range [-256, 255].
        ldr     x1, [x1, ___stack_chk_guard];momd
                         ^
util.s:8829:15: error: index must be an integer in range [-256, 255].
        ldr     x3, [x3, ___stack_chk_guard];momd
                         ^
util.s:8878:15: error: index must be an integer in range [-256, 255].
        ldr     x1, [x1, ___stack_chk_guard];momd
                         ^
util.s:8907:15: error: index must be an integer in range [-256, 255].
        ldr     x3, [x3, ___stack_chk_guard];momd
                         ^
util.s:8916:15: error: index must be an integer in range [-256, 255].
        ldr     x1, [x1, ___stack_chk_guard];momd
                         ^
util.s:8961:15: error: index must be an integer in range [-256, 255].
        ldr     x3, [x3, ___stack_chk_guard];momd
                         ^
util.s:9021:15: error: index must be an integer in range [-256, 255].
        ldr     x0, [x0, ___stack_chk_guard];momd
                         ^
util.s:9998:15: error: index must be an integer in range [-256, 255].
        ldr     x3, [x3, ___stack_chk_guard];momd
                         ^
util.s:10075:15: error: index must be an integer in range [-256, 255].
        ldr     x0, [x0, ___stack_chk_guard];momd
                         ^
ilg@xbbma perl-5.34.0 % 
```

Archive:

[util.zip](https://github.com/iains/gcc-darwin-arm64/files/7612883/util.zip)


I'll review the other packages that I currently compile with clang, perhaps we can identify more problems. Compiling the entire HomeBrew distribution with gcc would be an interesting experience.

**Comment by iains** [comment] 2021-11-28 08:06
This should work - but the problem is that the ___stack_chk_guard  symbol is not being indirected via the GOT ... it will take some investigation to see why.

Short-term work-around would be to remove "-fstack-protector-strong " from the options.

**Comment by ilg-ul** [comment] 2021-11-28 09:05
> Short-term work-around would be to remove "-fstack-protector-strong " from the options.

I checked and I could not find any reference to this option in my scripts, it must come from the configure step. For now I'll keep the workaround with clang.

**Comment by iains** [comment] 2021-11-29 00:05
fixed in https://github.com/iains/gcc-darwin-arm64/commit/a3a48770291014cf1a73a4d2e032fbe13c2deec6

**Closed by iains** 2021-11-29 00:05 UTC
